version: "3.7"
services: 
    nginx:
        build: ./nginx
        container_name: ng01
        ports: 
            - "8000:80"
        volumes: 
            - ./static:/src/backend/staticfiles
            - ./media:/home/app/web/mediafiles
        depends_on: 
            - backend
            - frontend
    
    backend:
        build: ./src/backend
        command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
        container_name: dg01
        volumes: 
            - ./static:/src/backend/staticfiles
            - ./media:/src/backend/mediafiles
        depends_on: 
            - postgres
        env_file: 
            - ./.env.prod
        expose: 
            - "8000"
    
    frontend:
        build: ./src/frontend/
        container_name: rj01
        ports: 
            - "3000:3000"
        environment: 
            - NODE_ENV=development
        volumes:
            - ./src/frontend/:/app/frontend
            - node-modules:/app/frontend/node_modules
        depends_on: 
            - backend
    
    postgres:
        image: postgres:latest
        volumes:
            - type : volume
              source : ./postgres_data
              target : /var/lib/postgresql/data
        container_name: ps01
        env_file: 
            - ./.env.prod
        ports:
            - "5432:5432"


#To persist the data beyond the life of the container we configured a volume.
#This config will bind postgres_data to the "/var/lib/postgresql/data/" directory in the container.
volumes:
    postgres_data:
    static:
    media: 
    node-modules: