version: "3.7"
services: 
    nginx:
        build: ./nginx
        container_name: ng01
        ports: 
            - "80:80"
        volumes: 
            - ./static:/src/backend/staticfiles
            - ./media:/src/backend/mediafiles
        depends_on: 
            - backend
            - frontend
    
    backend:
        build: ./src/backend
        command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
        container_name: dg01
        volumes: 
            - ./static:/src/backend/staticfiles
            - ./media:/src/backend/mediafiles
        depends_on: 
            - db
        env_file: 
            - ./.env.prod
        expose: 
            - "8000"
    
    frontend:
        build: ./src/frontend/
        container_name: rj01
        ports: 
            - "3000:3000"
        environment: 
            - NODE_ENV=development
        depends_on: 
            - backend
    
    db:
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        container_name: ps01
        env_file: 
            - ./.env.prod


#To persist the data beyond the life of the container we configured a volume.
#This config will bind postgres_data to the "/var/lib/postgresql/data/" directory in the container.
volumes:
    postgres_data:
    static:
    media: 